###### KEYBINDS ######

# remove *all* keybindings
unbind-key -a

# reload config

# reinsert regular tmux binds 
bind C-x lock-server
bind C-d detach
bind * list-clients

# manage windows
bind n new-window -c "$HOME"
bind H previous-window
bind L next-window
bind C-a last-window
bind C-w list-windows
bind w list-windows
bind | split-window
bind b split-window -v -c "#{pane_current_path}" # create horizontal split
bind v split-window -h -c "#{pane_current_path}" # create vertical split
bind '"' choose-window
bind r command-prompt "rename-window %%"
bind 0 select-window -t :=0
bind 1 select-window -t :=1
bind 2 select-window -t :=2
bind 3 select-window -t :=3
bind 4 select-window -t :=4
bind 5 select-window -t :=5
bind 6 select-window -t :=6
bind 7 select-window -t :=7
bind 8 select-window -t :=8
bind 9 select-window -t :=9
bind d kill-window

# manage panes
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind z resize-pane -Z
bind P set pane-border-status
bind x kill-pane
bind s swap-pane -D

# copy mode
bind c copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# Popups
bind o popup -E -d "#{pane_current_path}" -w 90% -h 90% "opencode"

# other 
bind : command-prompt
bind S choose-session
bind K send-keys "clear"\; send-keys "Enter"

# refresh client
bind C-R refresh-client

# reload config
bind C-r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

