###### KEYBINDS ######

# remove *all* keybindings
unbind-key -a

# reinsert regular tmux binds 
bind C-x lock-server
bind C-c new-window -c "$HOME"
bind C-d detach
bind * list-clients

# manage windows
bind H previous-window
bind L next-window
bind C-a last-window
bind C-w list-windows
bind w list-windows
bind | split-window
bind s split-window -v -c "#{pane_current_path}" # create horizontal split
bind v split-window -h -c "#{pane_current_path}" # create vertical split
bind '"' choose-window
bind r command-prompt "rename-window %%"

# manage panes
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind z resize-pane -Z
bind P set pane-border-status
bind c kill-pane
bind x swap-pane -D

# copy mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane 

# other 
bind ^L refresh-client
bind : command-prompt
bind S choose-session
bind K send-keys "clear"\; send-keys "Enter"

# reload config
bind R source-file ~/.config/tmux/tmux.conf

