source-file ~/.config/tmux/tmux.reset.conf
source-file ~/.config/tmux/tmux.theme.conf
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

set -g prefix C-a
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g mouse on                  # enable mouse
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}" # default terminal
setw -g mode-keys vi
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'
set -g allow-passthrough on     # Allow things like image previews
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -s extended-keys on # Allows applications to distinguish modifier keys properly

# install plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-floax'

# tmux-yank settings
set -g @yank_with_mouse off   # disallow yank with mouse
set -g @yank_action 'copy-pipe' # prevent exiting copy mode after yanking text

# floatx settings
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'blue'
set -g @floax-bind 'p'
set -g @floax-change-path 'true'

run ~/.config/tmux/plugins/tpm/tpm

