#################
### AUTOSTART ###
#################

# exec-once = $terminal
# exec-once = nm-applet &

# Locking, idling, wallpaper
exec-once = hyprlock & hypridle & hyprpaper

# Top status bar
exec-once = waybar

# Clipboard (clipse)
exec-once = clipse -listen
bind = SUPER, V, exec, ghostty --class clipse -e clipse

# Notifications
exec-once = swaync


