local vars = require("variables")

hl.on("hyprland.start", function()
	hl.exec_cmd("uwsm app -- " .. vars.terminal)
	hl.exec_cmd("uwsm app -- nm-applet --indicator")
	hl.exec_cmd("uwsm app -- hyprlock")
	hl.exec_cmd("uwsm app -- hypridle")
	hl.exec_cmd("uwsm app -- hyprpaper")
	hl.exec_cmd("uwsm app -- waybar")
	hl.exec_cmd("uwsm app -- clipse -listen")
	hl.exec_cmd("uwsm app -- swaync")
end)
