#################
### AUTOSTART ###
#################

# exec-once = uwsm app -- $terminal
exec-once = uwsm app -- nm-applet --indicator

# Locking, idling, wallpaper
exec-once = uwsm app -- hyprlock
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- hyprpaper

# Top status bar
exec-once = uwsm app -- waybar

# Clipboard (clipse)
exec-once = uwsm app -- clipse -listen
bind = SUPER, V, exec, uwsm app -- ghostty --class clipse -e clipse

# Notifications
exec-once = uwsm app -- swaync
